### PR TITLE
Add esm support

### PR DESCRIPTION
**Pull request by TrySound**
Hey! I'd like to add es modules support to this module. There are a few
reasons for that

- one step forward for ecosystem where we could get rid from commonjs in
favour of standard
- rollup bundler could build this dependency without commonjs plugin
which converts cjs to esm
- jss-plugin-camel-case project could be used directly in the browser
with the help of unpkg service

```js
import camelCase from 'https://unpkg.com/jss-plugin-camel-case@next?module'
```

I used rollup to convert esm to cjs because it has only a few small
dependencies and is the only clean way to provide `module.exports`
instead of `exports.default`.

### CODE REVIEW

**Comment by TrySound** [comment]
@rexxars I can split lint tweak and node upgrade in separate PRs if you want.

**Comment by rexxars** [comment]
Thanks a bunch for this. Will publish a new release in a bit, just want your input on the lockfile commit first.

**Comment by rexxars** [comment]
Released as v1.0.3

**Comment by TrySound** [comment]
Thanks

**Comment by Cretezy** [comment]
I know this is long dead, but this is causing issues with Vite. Specifically, other modules are trying to introp with `_interopRequireDefault`, but since this doesn't have `__esModule` as true (likely a Vite issue), it's not working. Downgrading to 1.0.2 makes it work

**Comment by TrySound** [comment]
You mean some commonjs code is trying to import this library?

**Comment by Cretezy** [comment]
```
hyphenateProperty.js:15 Uncaught TypeError: (0 , _hyphenateStyleName2.default) is not a function
    at hyphenateProperty (hyphenateProperty.js:15)
    at prefixValue (transition.js:50)
    at Array.transition2 (transition.js:70)
    at prefixValue (prefixValue.js:9)
    at prefix2 (createPrefixer.js:52)
    at createDeclarationBlock (compile.js:230)
    at createAtomicRules (compile.js:215)
    at compile.js:54
    at Array.reduce (<anonymous>)
    at atomic (compile.js:41)
```

From `css-in-js-utils`. It's trying to do `.default` on the default already.

**Comment by TrySound** [comment]
Latest version has es modules support. Shouldn't be a problem.
https://github.com/robinweser/css-in-js-utils/blob/master/package.json#L6

**Comment by Cretezy** [comment]
Somehow the issue _is_ that it's an ES module. We changes our approach so it's not really an issue anymore

**Pull request merged**
